//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace l4_ex2_formApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        l4_ex2_formApp.ServiceReference1.HelloWorldResponse HelloWorld(l4_ex2_formApp.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<l4_ex2_formApp.ServiceReference1.HelloWorldResponse> HelloWorldAsync(l4_ex2_formApp.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/convFtoC", ReplyAction="*")]
        double convFtoC(double f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/convFtoC", ReplyAction="*")]
        System.Threading.Tasks.Task<double> convFtoCAsync(double f);
        
        // CODEGEN: Generating message contract since element name getCurrentDateAndTimeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCurrentDateAndTime", ReplyAction="*")]
        l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeResponse getCurrentDateAndTime(l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCurrentDateAndTime", ReplyAction="*")]
        System.Threading.Tasks.Task<l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeResponse> getCurrentDateAndTimeAsync(l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeRequest request);
        
        // CODEGEN: Generating message contract since element name getListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getList", ReplyAction="*")]
        l4_ex2_formApp.ServiceReference1.getListResponse getList(l4_ex2_formApp.ServiceReference1.getListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getList", ReplyAction="*")]
        System.Threading.Tasks.Task<l4_ex2_formApp.ServiceReference1.getListResponse> getListAsync(l4_ex2_formApp.ServiceReference1.getListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/convertRonToE", ReplyAction="*")]
        double convertRonToE(double ron);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/convertRonToE", ReplyAction="*")]
        System.Threading.Tasks.Task<double> convertRonToEAsync(double ron);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public l4_ex2_formApp.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(l4_ex2_formApp.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public l4_ex2_formApp.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(l4_ex2_formApp.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCurrentDateAndTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCurrentDateAndTime", Namespace="http://tempuri.org/", Order=0)]
        public l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeRequestBody Body;
        
        public getCurrentDateAndTimeRequest() {
        }
        
        public getCurrentDateAndTimeRequest(l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getCurrentDateAndTimeRequestBody {
        
        public getCurrentDateAndTimeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCurrentDateAndTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCurrentDateAndTimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeResponseBody Body;
        
        public getCurrentDateAndTimeResponse() {
        }
        
        public getCurrentDateAndTimeResponse(l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCurrentDateAndTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getCurrentDateAndTimeResult;
        
        public getCurrentDateAndTimeResponseBody() {
        }
        
        public getCurrentDateAndTimeResponseBody(string getCurrentDateAndTimeResult) {
            this.getCurrentDateAndTimeResult = getCurrentDateAndTimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getList", Namespace="http://tempuri.org/", Order=0)]
        public l4_ex2_formApp.ServiceReference1.getListRequestBody Body;
        
        public getListRequest() {
        }
        
        public getListRequest(l4_ex2_formApp.ServiceReference1.getListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getListRequestBody {
        
        public getListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListResponse", Namespace="http://tempuri.org/", Order=0)]
        public l4_ex2_formApp.ServiceReference1.getListResponseBody Body;
        
        public getListResponse() {
        }
        
        public getListResponse(l4_ex2_formApp.ServiceReference1.getListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public l4_ex2_formApp.ServiceReference1.ArrayOfInt getListResult;
        
        public getListResponseBody() {
        }
        
        public getListResponseBody(l4_ex2_formApp.ServiceReference1.ArrayOfInt getListResult) {
            this.getListResult = getListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : l4_ex2_formApp.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<l4_ex2_formApp.ServiceReference1.WebService1Soap>, l4_ex2_formApp.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        l4_ex2_formApp.ServiceReference1.HelloWorldResponse l4_ex2_formApp.ServiceReference1.WebService1Soap.HelloWorld(l4_ex2_formApp.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            l4_ex2_formApp.ServiceReference1.HelloWorldRequest inValue = new l4_ex2_formApp.ServiceReference1.HelloWorldRequest();
            inValue.Body = new l4_ex2_formApp.ServiceReference1.HelloWorldRequestBody();
            l4_ex2_formApp.ServiceReference1.HelloWorldResponse retVal = ((l4_ex2_formApp.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<l4_ex2_formApp.ServiceReference1.HelloWorldResponse> l4_ex2_formApp.ServiceReference1.WebService1Soap.HelloWorldAsync(l4_ex2_formApp.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<l4_ex2_formApp.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            l4_ex2_formApp.ServiceReference1.HelloWorldRequest inValue = new l4_ex2_formApp.ServiceReference1.HelloWorldRequest();
            inValue.Body = new l4_ex2_formApp.ServiceReference1.HelloWorldRequestBody();
            return ((l4_ex2_formApp.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public double convFtoC(double f) {
            return base.Channel.convFtoC(f);
        }
        
        public System.Threading.Tasks.Task<double> convFtoCAsync(double f) {
            return base.Channel.convFtoCAsync(f);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeResponse l4_ex2_formApp.ServiceReference1.WebService1Soap.getCurrentDateAndTime(l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeRequest request) {
            return base.Channel.getCurrentDateAndTime(request);
        }
        
        public string getCurrentDateAndTime() {
            l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeRequest inValue = new l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeRequest();
            inValue.Body = new l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeRequestBody();
            l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeResponse retVal = ((l4_ex2_formApp.ServiceReference1.WebService1Soap)(this)).getCurrentDateAndTime(inValue);
            return retVal.Body.getCurrentDateAndTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeResponse> l4_ex2_formApp.ServiceReference1.WebService1Soap.getCurrentDateAndTimeAsync(l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeRequest request) {
            return base.Channel.getCurrentDateAndTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeResponse> getCurrentDateAndTimeAsync() {
            l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeRequest inValue = new l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeRequest();
            inValue.Body = new l4_ex2_formApp.ServiceReference1.getCurrentDateAndTimeRequestBody();
            return ((l4_ex2_formApp.ServiceReference1.WebService1Soap)(this)).getCurrentDateAndTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        l4_ex2_formApp.ServiceReference1.getListResponse l4_ex2_formApp.ServiceReference1.WebService1Soap.getList(l4_ex2_formApp.ServiceReference1.getListRequest request) {
            return base.Channel.getList(request);
        }
        
        public l4_ex2_formApp.ServiceReference1.ArrayOfInt getList() {
            l4_ex2_formApp.ServiceReference1.getListRequest inValue = new l4_ex2_formApp.ServiceReference1.getListRequest();
            inValue.Body = new l4_ex2_formApp.ServiceReference1.getListRequestBody();
            l4_ex2_formApp.ServiceReference1.getListResponse retVal = ((l4_ex2_formApp.ServiceReference1.WebService1Soap)(this)).getList(inValue);
            return retVal.Body.getListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<l4_ex2_formApp.ServiceReference1.getListResponse> l4_ex2_formApp.ServiceReference1.WebService1Soap.getListAsync(l4_ex2_formApp.ServiceReference1.getListRequest request) {
            return base.Channel.getListAsync(request);
        }
        
        public System.Threading.Tasks.Task<l4_ex2_formApp.ServiceReference1.getListResponse> getListAsync() {
            l4_ex2_formApp.ServiceReference1.getListRequest inValue = new l4_ex2_formApp.ServiceReference1.getListRequest();
            inValue.Body = new l4_ex2_formApp.ServiceReference1.getListRequestBody();
            return ((l4_ex2_formApp.ServiceReference1.WebService1Soap)(this)).getListAsync(inValue);
        }
        
        public double convertRonToE(double ron) {
            return base.Channel.convertRonToE(ron);
        }
        
        public System.Threading.Tasks.Task<double> convertRonToEAsync(double ron) {
            return base.Channel.convertRonToEAsync(ron);
        }
    }
}
