//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name getAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAll", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.getAllResponse getAll(WindowsFormsApp1.ServiceReference1.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAll", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.getAllResponse> getAllAsync(WindowsFormsApp1.ServiceReference1.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertNr", ReplyAction="*")]
        void insertNr(int nrToInsert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertNr", ReplyAction="*")]
        System.Threading.Tasks.Task insertNrAsync(int nrToInsert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateNr", ReplyAction="*")]
        void updateNr(int newValue, int idToUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateNr", ReplyAction="*")]
        System.Threading.Tasks.Task updateNrAsync(int newValue, int idToUpdate);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAll", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.getAllRequestBody Body;
        
        public getAllRequest() {
        }
        
        public getAllRequest(WindowsFormsApp1.ServiceReference1.getAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllRequestBody {
        
        public getAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.getAllResponseBody Body;
        
        public getAllResponse() {
        }
        
        public getAllResponse(WindowsFormsApp1.ServiceReference1.getAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceReference1.ArrayOfInt getAllResult;
        
        public getAllResponseBody() {
        }
        
        public getAllResponseBody(WindowsFormsApp1.ServiceReference1.ArrayOfInt getAllResult) {
            this.getAllResult = getAllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.WebService1Soap>, WindowsFormsApp1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.getAllResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.getAll(WindowsFormsApp1.ServiceReference1.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public WindowsFormsApp1.ServiceReference1.ArrayOfInt getAll() {
            WindowsFormsApp1.ServiceReference1.getAllRequest inValue = new WindowsFormsApp1.ServiceReference1.getAllRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.getAllRequestBody();
            WindowsFormsApp1.ServiceReference1.getAllResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).getAll(inValue);
            return retVal.Body.getAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.getAllResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.getAllAsync(WindowsFormsApp1.ServiceReference1.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.getAllResponse> getAllAsync() {
            WindowsFormsApp1.ServiceReference1.getAllRequest inValue = new WindowsFormsApp1.ServiceReference1.getAllRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.getAllRequestBody();
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).getAllAsync(inValue);
        }
        
        public void insertNr(int nrToInsert) {
            base.Channel.insertNr(nrToInsert);
        }
        
        public System.Threading.Tasks.Task insertNrAsync(int nrToInsert) {
            return base.Channel.insertNrAsync(nrToInsert);
        }
        
        public void updateNr(int newValue, int idToUpdate) {
            base.Channel.updateNr(newValue, idToUpdate);
        }
        
        public System.Threading.Tasks.Task updateNrAsync(int newValue, int idToUpdate) {
            return base.Channel.updateNrAsync(newValue, idToUpdate);
        }
    }
}
